baseurl = "/"
title = "The Art Of Computer Science"
copyright = "Copyright (c) 2018, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

[author]
  name = "Wesam Haboush"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: native, vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/posts/"

#[[menu.main]]
#  name = "Tags"
#  weight = -110
#  identifier = "tag"
#  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."

[params]
  github = "wesamhaboush"
#  gitlab = "gitlab id"
#  twitter = "twitter id"
  linkedin = "wesam-haboush-10609b3b"
  email = "wesam.haboush@outlook.com"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
